folders:
  - ./:
      struct:
        - github/workflows/pre-commit
        - github/workflows/run-struct
        - configs/editor-config
        - configs/prettier
      with:
        github_token: ${{ secrets.STRUCT_RUN_TOKEN }}
