name: z-pre-commit

on:
  pull_request:
    branches: [DEFAULT_BRANCH_ERROR]
  push:
    branches: [DEFAULT_BRANCH_ERROR]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-python@v5.6.0
    - uses: pre-commit/action@v3.0.1
